/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminImport } from './routes/admin'
import { Route as LayoutImport } from './routes/_layout'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as AdminReportsImport } from './routes/admin/reports'
import { Route as LayoutWeddingImport } from './routes/_layout/wedding'
import { Route as LayoutShopImport } from './routes/_layout/shop'
import { Route as LayoutPartnersImport } from './routes/_layout/partners'
import { Route as LayoutLocationsImport } from './routes/_layout/locations'
import { Route as LayoutFranchiseImport } from './routes/_layout/franchise'
import { Route as LayoutBookingImport } from './routes/_layout/booking'
import { Route as LayoutAboutImport } from './routes/_layout/about'
import { Route as AdminStaffIndexImport } from './routes/admin/staff/index'
import { Route as AdminServicesIndexImport } from './routes/admin/services/index'
import { Route as AdminCustomersIndexImport } from './routes/admin/customers/index'
import { Route as AdminBookingsIndexImport } from './routes/admin/bookings/index'
import { Route as LayoutServicesHairCutIndexImport } from './routes/_layout/services/hair-cut/index'
import { Route as AdminServicesIdEditImport } from './routes/admin/services/$id.edit'
import { Route as LayoutServicesHairCutIdImport } from './routes/_layout/services/hair-cut/$id'

// Create/Update Routes

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const AdminReportsRoute = AdminReportsImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)

const LayoutWeddingRoute = LayoutWeddingImport.update({
  id: '/wedding',
  path: '/wedding',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutShopRoute = LayoutShopImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPartnersRoute = LayoutPartnersImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLocationsRoute = LayoutLocationsImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutFranchiseRoute = LayoutFranchiseImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutBookingRoute = LayoutBookingImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAboutRoute = LayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)

const AdminStaffIndexRoute = AdminStaffIndexImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminServicesIndexRoute = AdminServicesIndexImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminCustomersIndexRoute = AdminCustomersIndexImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminBookingsIndexRoute = AdminBookingsIndexImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AdminRoute,
} as any)

const LayoutServicesHairCutIndexRoute = LayoutServicesHairCutIndexImport.update(
  {
    id: '/services/hair-cut/',
    path: '/services/hair-cut/',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const AdminServicesIdEditRoute = AdminServicesIdEditImport.update({
  id: '/services/$id/edit',
  path: '/services/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

const LayoutServicesHairCutIdRoute = LayoutServicesHairCutIdImport.update({
  id: '/services/hair-cut/$id',
  path: '/services/hair-cut/$id',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/booking': {
      id: '/_layout/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof LayoutBookingImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/franchise': {
      id: '/_layout/franchise'
      path: '/franchise'
      fullPath: '/franchise'
      preLoaderRoute: typeof LayoutFranchiseImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/locations': {
      id: '/_layout/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LayoutLocationsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/partners': {
      id: '/_layout/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof LayoutPartnersImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/shop': {
      id: '/_layout/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof LayoutShopImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/wedding': {
      id: '/_layout/wedding'
      path: '/wedding'
      fullPath: '/wedding'
      preLoaderRoute: typeof LayoutWeddingImport
      parentRoute: typeof LayoutImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsImport
      parentRoute: typeof AdminImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/services/': {
      id: '/admin/services/'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/staff/': {
      id: '/admin/staff/'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffIndexImport
      parentRoute: typeof AdminImport
    }
    '/_layout/services/hair-cut/$id': {
      id: '/_layout/services/hair-cut/$id'
      path: '/services/hair-cut/$id'
      fullPath: '/services/hair-cut/$id'
      preLoaderRoute: typeof LayoutServicesHairCutIdImport
      parentRoute: typeof LayoutImport
    }
    '/admin/services/$id/edit': {
      id: '/admin/services/$id/edit'
      path: '/services/$id/edit'
      fullPath: '/admin/services/$id/edit'
      preLoaderRoute: typeof AdminServicesIdEditImport
      parentRoute: typeof AdminImport
    }
    '/_layout/services/hair-cut/': {
      id: '/_layout/services/hair-cut/'
      path: '/services/hair-cut'
      fullPath: '/services/hair-cut'
      preLoaderRoute: typeof LayoutServicesHairCutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutBookingRoute: typeof LayoutBookingRoute
  LayoutFranchiseRoute: typeof LayoutFranchiseRoute
  LayoutLocationsRoute: typeof LayoutLocationsRoute
  LayoutPartnersRoute: typeof LayoutPartnersRoute
  LayoutShopRoute: typeof LayoutShopRoute
  LayoutWeddingRoute: typeof LayoutWeddingRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutServicesHairCutIdRoute: typeof LayoutServicesHairCutIdRoute
  LayoutServicesHairCutIndexRoute: typeof LayoutServicesHairCutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutBookingRoute: LayoutBookingRoute,
  LayoutFranchiseRoute: LayoutFranchiseRoute,
  LayoutLocationsRoute: LayoutLocationsRoute,
  LayoutPartnersRoute: LayoutPartnersRoute,
  LayoutShopRoute: LayoutShopRoute,
  LayoutWeddingRoute: LayoutWeddingRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutServicesHairCutIdRoute: LayoutServicesHairCutIdRoute,
  LayoutServicesHairCutIndexRoute: LayoutServicesHairCutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AdminRouteChildren {
  AdminReportsRoute: typeof AdminReportsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute
  AdminStaffIndexRoute: typeof AdminStaffIndexRoute
  AdminServicesIdEditRoute: typeof AdminServicesIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminReportsRoute: AdminReportsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminServicesIndexRoute: AdminServicesIndexRoute,
  AdminStaffIndexRoute: AdminStaffIndexRoute,
  AdminServicesIdEditRoute: AdminServicesIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/about': typeof LayoutAboutRoute
  '/booking': typeof LayoutBookingRoute
  '/franchise': typeof LayoutFranchiseRoute
  '/locations': typeof LayoutLocationsRoute
  '/partners': typeof LayoutPartnersRoute
  '/shop': typeof LayoutShopRoute
  '/wedding': typeof LayoutWeddingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/': typeof LayoutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/services': typeof AdminServicesIndexRoute
  '/admin/staff': typeof AdminStaffIndexRoute
  '/services/hair-cut/$id': typeof LayoutServicesHairCutIdRoute
  '/admin/services/$id/edit': typeof AdminServicesIdEditRoute
  '/services/hair-cut': typeof LayoutServicesHairCutIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof LayoutAboutRoute
  '/booking': typeof LayoutBookingRoute
  '/franchise': typeof LayoutFranchiseRoute
  '/locations': typeof LayoutLocationsRoute
  '/partners': typeof LayoutPartnersRoute
  '/shop': typeof LayoutShopRoute
  '/wedding': typeof LayoutWeddingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/': typeof LayoutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/services': typeof AdminServicesIndexRoute
  '/admin/staff': typeof AdminStaffIndexRoute
  '/services/hair-cut/$id': typeof LayoutServicesHairCutIdRoute
  '/admin/services/$id/edit': typeof AdminServicesIdEditRoute
  '/services/hair-cut': typeof LayoutServicesHairCutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/booking': typeof LayoutBookingRoute
  '/_layout/franchise': typeof LayoutFranchiseRoute
  '/_layout/locations': typeof LayoutLocationsRoute
  '/_layout/partners': typeof LayoutPartnersRoute
  '/_layout/shop': typeof LayoutShopRoute
  '/_layout/wedding': typeof LayoutWeddingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/admin/staff/': typeof AdminStaffIndexRoute
  '/_layout/services/hair-cut/$id': typeof LayoutServicesHairCutIdRoute
  '/admin/services/$id/edit': typeof AdminServicesIdEditRoute
  '/_layout/services/hair-cut/': typeof LayoutServicesHairCutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/admin'
    | '/about'
    | '/booking'
    | '/franchise'
    | '/locations'
    | '/partners'
    | '/shop'
    | '/wedding'
    | '/admin/reports'
    | '/'
    | '/admin/'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/services'
    | '/admin/staff'
    | '/services/hair-cut/$id'
    | '/admin/services/$id/edit'
    | '/services/hair-cut'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/booking'
    | '/franchise'
    | '/locations'
    | '/partners'
    | '/shop'
    | '/wedding'
    | '/admin/reports'
    | '/'
    | '/admin'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/services'
    | '/admin/staff'
    | '/services/hair-cut/$id'
    | '/admin/services/$id/edit'
    | '/services/hair-cut'
  id:
    | '__root__'
    | '/_layout'
    | '/admin'
    | '/_layout/about'
    | '/_layout/booking'
    | '/_layout/franchise'
    | '/_layout/locations'
    | '/_layout/partners'
    | '/_layout/shop'
    | '/_layout/wedding'
    | '/admin/reports'
    | '/_layout/'
    | '/admin/'
    | '/admin/bookings/'
    | '/admin/customers/'
    | '/admin/services/'
    | '/admin/staff/'
    | '/_layout/services/hair-cut/$id'
    | '/admin/services/$id/edit'
    | '/_layout/services/hair-cut/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/admin"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/about",
        "/_layout/booking",
        "/_layout/franchise",
        "/_layout/locations",
        "/_layout/partners",
        "/_layout/shop",
        "/_layout/wedding",
        "/_layout/",
        "/_layout/services/hair-cut/$id",
        "/_layout/services/hair-cut/"
      ]
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/reports",
        "/admin/",
        "/admin/bookings/",
        "/admin/customers/",
        "/admin/services/",
        "/admin/staff/",
        "/admin/services/$id/edit"
      ]
    },
    "/_layout/about": {
      "filePath": "_layout/about.tsx",
      "parent": "/_layout"
    },
    "/_layout/booking": {
      "filePath": "_layout/booking.tsx",
      "parent": "/_layout"
    },
    "/_layout/franchise": {
      "filePath": "_layout/franchise.tsx",
      "parent": "/_layout"
    },
    "/_layout/locations": {
      "filePath": "_layout/locations.tsx",
      "parent": "/_layout"
    },
    "/_layout/partners": {
      "filePath": "_layout/partners.tsx",
      "parent": "/_layout"
    },
    "/_layout/shop": {
      "filePath": "_layout/shop.tsx",
      "parent": "/_layout"
    },
    "/_layout/wedding": {
      "filePath": "_layout/wedding.tsx",
      "parent": "/_layout"
    },
    "/admin/reports": {
      "filePath": "admin/reports.tsx",
      "parent": "/admin"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/admin/bookings/": {
      "filePath": "admin/bookings/index.tsx",
      "parent": "/admin"
    },
    "/admin/customers/": {
      "filePath": "admin/customers/index.tsx",
      "parent": "/admin"
    },
    "/admin/services/": {
      "filePath": "admin/services/index.tsx",
      "parent": "/admin"
    },
    "/admin/staff/": {
      "filePath": "admin/staff/index.tsx",
      "parent": "/admin"
    },
    "/_layout/services/hair-cut/$id": {
      "filePath": "_layout/services/hair-cut/$id.tsx",
      "parent": "/_layout"
    },
    "/admin/services/$id/edit": {
      "filePath": "admin/services/$id.edit.tsx",
      "parent": "/admin"
    },
    "/_layout/services/hair-cut/": {
      "filePath": "_layout/services/hair-cut/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
